In [1]:
import numpy as np
import pandas as pd
import platform
print(platform.python_version())


print(note:= "some basics of numpy before we jump on to pandas")


3.9.0
some basics of numpy before we jump on to pandas


In [2]:
print( note:= "this is python based list")
print( note:= "python list can have diff type of data like string,  int, float, char etc etc etc") 
sample_list = ['a', 1 , 1.2 , '3', 'welcome']

print()
print(note:="we shall see the data as its own type")
print(sample_list)

this is python based list
python list can have diff type of data like string,  int, float, char etc etc etc

we shall see the data as its own type
['a', 1, 1.2, '3', 'welcome']


In [3]:
print(note:='we shall see the data as string type as we have mixed data type')
print(sr := np.array(sample_list))

we shall see the data as string type as we have mixed data type
['a' '1' '1.2' '3' 'welcome']


In [4]:
print(note:= "we can get the dimention of array through shape attribue of arrays")
print(sr.shape) 

we can get the dimention of array through shape attribue of arrays
(5,)


In [5]:
print(note:= "we can get  type of array")
print(sr.dtype)

we can get  type of array
<U7


In [6]:
print(note := "if we use only int data, we shall see the respective in type")
i1r = np.array([1,2,3])
print(i1r.dtype)

if we use only int data, we shall see the respective in type
int64


In [7]:
print(note:= "we can use indexing")
print(i1r[0], i1r[1], i1r[2])

we can use indexing
1 2 3


In [8]:
print(note := "we can create list within list, which is sort of a matrix")
i2r = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i2r.shape)
print(i2r.dtype)

we can create list within list, which is sort of a matrix
(3, 3)
int64


In [9]:
print(note:= "we can use indexing")
# : indexing follow the the patterm of range, start is includes, end is not included'
print(i2r[0], i2r[1], i2r[0,1:3], i2r[1,0:2], i2r[1,0:2])
print()
print(i2r[2,:])
print()
print(i2r[:,:])

we can use indexing
[1 2 3] [4 5 6] [2 3] [4 5] [4 5]

[7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#returns true if any value is true or non-zero
print(i2r.any())
zero = i2r - i2r 
print(zero.any())

True
False


In [11]:
#returns true if all the values are true or non-zero
print(i2r.all())
print(note:= "we can do scalar operations on np array")
i2r = i2r - 1
print(i2r.all())

True
we can do scalar operations on np array
False


In [12]:
# sum returns sum of the array
print(i2r.sum())

36


In [13]:
print(note := "we can specify axis information in many of numpy functions")
print()
# 0 is each coloums 
print(i2r.sum(0))
print()
# 1 is rows 
print(i2r.sum(1))

we can specify axis information in many of numpy functions

[ 9 12 15]

[ 3 12 21]


In [14]:
# we can get mean
print(i2r.mean())

4.0


In [15]:
# mean also supports the axis info
print(i2r.mean(0))
print()
print(i2r.mean(1))

[3. 4. 5.]

[1. 4. 7.]


In [16]:
# we can also get std 
print(i2r.std())


2.581988897471611


In [17]:
# std also supports the axis information
print(i2r.std(0))
print()
print(i2r.std(1))

[2.44948974 2.44948974 2.44948974]

[0.81649658 0.81649658 0.81649658]


In [18]:
print(note:= "np has arange function to create range of values")
n1r = np.arange(0, 40)
print(n1r)

np has arange function to create range of values
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [19]:
print(note:= "it also has reshape function to shape the values")
n2r = np.arange(0,40,2).reshape(4,5)
print(n2r)

it also has reshape function to shape the values
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [20]:
# the way you want !!!
n3r = np.arange(0,40,2).reshape(2,5,2)
print(n3r)

[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]
  [16 18]]

 [[20 22]
  [24 26]
  [28 30]
  [32 34]
  [36 38]]]


In [21]:
# np also has support to generate random number
nr = np.random.randn(20).reshape(4,5)
print(nr)

[[ 0.74967232  1.07002155  2.09854485 -1.6225968  -0.81362517]
 [ 0.17373693  0.35435876  1.09133242 -0.68463918 -0.61942004]
 [-0.44343363 -0.49688101  0.62710486 -0.88137442 -1.57035669]
 [ 0.1957441  -1.40392937 -0.4378541   0.97903103  1.88980787]]


## PANDAS

### basic of series

In [22]:
# lets first have a quick look at series
# series is like an array but is indexed

iis = pd.Series([11,12,31,41,15,61,17,80])
print(iis)

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: int64


In [23]:
# and unlike numpy we can have mixed data types 
ms = pd.Series([11,12,'31',41,15,61,'17',80])
print(ms)

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: object


In [24]:
# we can get the values
# and notice that data still is in original type as passed
ms.values

array([11, 12, '31', 41, 15, 61, '17', 80], dtype=object)

In [25]:
# we can get the indexs
print(ms.index)
print()
# index have important role in pandas as we can use them more numerous operations 
type(ms.index)

RangeIndex(start=0, stop=8, step=1)



pandas.core.indexes.range.RangeIndex

In [26]:
#we can determine the type of data
print(iis.dtype)
# not the type is from numpy class 
# pandas uses numpy internally 
print(type(iis.dtype))
print(ms.dtype)
print(type(ms.dtype))

int64
<class 'numpy.dtype'>
object
<class 'numpy.dtype'>


In [27]:
#we can determine the size of data
ms.size

8

In [28]:
# or shape 
ms.shape

(8,)

In [29]:
#we can get the number of bytes used to store the data 
print(ms.nbytes)

64


In [30]:
# we can use the index to access the values 
print(ms[5])
print(ms[6])
print(type(ms[5]))
print(type(ms[6]))

61
17
<class 'int'>
<class 'str'>


In [31]:
# we can also get values based on conditions
iis[iis > 40]

3    41
5    61
7    80
dtype: int64

In [32]:
# but this will fail , as str and int can't be compared with >
# ms[ms>40]

In [33]:
# we can use our own indexes rather than using the default index values
# here is the number covid cases in million and respective countries as index
cd = pd.Series([100.3, 80.64, 50.7, 10.83, 10.82], index=['usa','ind','bra','frc','rus'])
# this is how pandas are beautiful, rather than relying on index like in excel we can have representative 
print(cd)

usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
dtype: float64


In [34]:
# we can name our series 
cd.name = 'covid_cases'
# we can also name the index
cd.index.name = 'countries'
cd

countries
usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
Name: covid_cases, dtype: float64

In [35]:
cd.index

Index(['usa', 'ind', 'bra', 'frc', 'rus'], dtype='object', name='countries')

In [36]:
# we can check if key exists in index, with "in"
'ind' in cd.index

True

In [37]:
'chn' in cd.index

False

In [38]:
index_p = cd.index
# we can get the indexes via int index
index_p[0]

'usa'

In [39]:
# this would fail
# index are immutable 
#index_p[0] = 'temp'

In [40]:
# we can use the list like slicing 
index_p[:2]

Index(['usa', 'ind'], dtype='object', name='countries')

In [41]:
index_p[-1]

'rus'

In [42]:
# what would this print?
# index_p[:-1]

In [43]:
# as index are immutable and can't be changed directly 
# we need to use reindex if we want to change them 
# if new index is added we shall NaN
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'])
ncd

countries
usa    100.30
ind     80.64
frc     10.83
rus     10.82
esp       NaN
bra     50.70
Name: covid_cases, dtype: float64

In [44]:
# we can use fill_value to specify the default falue if index is not already present
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'], fill_value='0')
ncd

countries
usa    100.3
ind    80.64
frc    10.83
rus    10.82
esp        0
bra     50.7
Name: covid_cases, dtype: object

In [45]:
#we can convert the series to a python dict 
pcd = ncd.to_dict()
pcd

{'usa': 100.3,
 'ind': 80.64,
 'frc': 10.83,
 'rus': 10.82,
 'esp': '0',
 'bra': 50.7}

In [46]:
#we can pass a dict to series to create a series
bcd = pd.Series(pcd)
# the extra info that we added like name of index etc will be lost 
bcd

usa    100.3
ind    80.64
frc    10.83
rus    10.82
esp        0
bra     50.7
dtype: object

In [47]:
# we can also specify our own index/keys while passing the dict
nbcd = pd.Series(pcd, index=['usa','ind','bra','frc','rus','esp','chn'])
nbcd

usa    100.3
ind    80.64
bra     50.7
frc    10.83
rus    10.82
esp        0
chn      NaN
dtype: object

In [48]:
# as chn was not part of the dict already we got a new key with NaN value
# we can check if we have null values in our series
pd.isnull(nbcd)

usa    False
ind    False
bra    False
frc    False
rus    False
esp    False
chn     True
dtype: bool

In [49]:
# we can also use notnull to check what all values are not null in the series
pd.notnull(nbcd)

usa     True
ind     True
bra     True
frc     True
rus     True
esp     True
chn    False
dtype: bool

### basics of dataframe

In [50]:
# lets first have a quick look at dataframe
rank_dict = { \
             'year' : [2019,2018,2017,2016,2015], \
             'batsman':['virat kohli', 'virat kohli', 'steve smith', 'steve smith', 'steve smith' ],\
             'batsman country': ['india', 'india', 'australia', 'australia', 'australia'],\
             'bowler': ['Pat Cummins', 'Kagiso Rabada', 'James Anderson', 'James Anderson', 'Ravichandran Ashwin' ],\
            'bowler country':['australia', 'South Africa', 'England', 'India', 'India' ]\
            }
# we can pass a dict that contains key as the coloum name and list as the respective values 
icc_ranking = pd.DataFrame(rank_dict)
icc_ranking

year      batsman batsman country               bowler bowler country
0  2019  virat kohli           india          Pat Cummins      australia
1  2018  virat kohli           india        Kagiso Rabada   South Africa
2  2017  steve smith       australia       James Anderson        England
3  2016  steve smith       australia       James Anderson          India
4  2015  steve smith       australia  Ravichandran Ashwin          India

In [51]:
# pandas automatically adds the indexes as shown above
# we can get the coloum names of the dataframe 
icc_ranking.columns

Index(['year', 'batsman', 'batsman country', 'bowler', 'bowler country'], dtype='object')

In [52]:
# we can also provide index names 
icc_ranking = pd.DataFrame(rank_dict, index=['19','18','17','16','15'])
icc_ranking

year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
18  2018  virat kohli           india        Kagiso Rabada   South Africa
17  2017  steve smith       australia       James Anderson        England
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [53]:
# we can use the coloum names to get the data 
icc_ranking.year

19    2019
18    2018
17    2017
16    2016
15    2015
Name: year, dtype: int64

In [54]:
# or we can use 
icc_ranking['batsman']

19    virat kohli
18    virat kohli
17    steve smith
16    steve smith
15    steve smith
Name: batsman, dtype: object

In [55]:
# for column name that has the spaces in middle we have to use the index approach 
# so always use index approach 
icc_ranking['bowler country']

19       australia
18    South Africa
17         England
16           India
15           India
Name: bowler country, dtype: object

In [56]:
# we can also retrive some values from dataframe 
# in this case 2 values from the start
icc_ranking.head(2)

year      batsman batsman country         bowler bowler country
19  2019  virat kohli           india    Pat Cummins      australia
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [57]:
# in this case 2 values from the start
icc_ranking.tail(2)

year      batsman batsman country               bowler bowler country
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [58]:
# we can also extract data at particular index with the help of iloc
icc_ranking.iloc[3]

year                         2016
batsman               steve smith
batsman country         australia
bowler             James Anderson
bowler country              India
Name: 16, dtype: object

In [59]:
# we can also select multiple index
icc_ranking.iloc[['0','2','4']]

year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
17  2017  steve smith       australia       James Anderson        England
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [60]:
# we can also extract multiple columns from the data frame
# this basically creates a new dataframe with selected coloums
pd.DataFrame(icc_ranking, columns=['year', 'batsman', 'batsman country'])

year      batsman batsman country
19  2019  virat kohli           india
18  2018  virat kohli           india
17  2017  steve smith       australia
16  2016  steve smith       australia
15  2015  steve smith       australia

In [61]:
# we can also extract multiple columns from the data frame
# if we pass a coloum name that does not exists we shall get NaN values
pd.DataFrame(icc_ranking, columns=['year', 'bowler', 'bowler country', 'notdefined'])

year               bowler bowler country  notdefined
19  2019          Pat Cummins      australia         NaN
18  2018        Kagiso Rabada   South Africa         NaN
17  2017       James Anderson        England         NaN
16  2016       James Anderson          India         NaN
15  2015  Ravichandran Ashwin          India         NaN

In [62]:
# let us create a Dataframe from numbers and provide user defined index and coloum names
df = pd.DataFrame(np.random.randn(20).reshape(4,5), index = ['first','second', 'third','fourth'], columns=['cl1', 'cl2', 'cl3','cl4','cl5'])
df

cl1       cl2       cl3       cl4       cl5
first  -0.157623 -1.414416  0.675708  0.549411  1.665969
second -0.492437  0.685788  0.215040  0.252677 -0.997441
third   0.075487  0.560347 -0.242204 -0.564074  0.122896
fourth  0.466901  0.131506 -1.734850 -2.421723 -0.738227

In [63]:
# we can reindex the DataFrame
# and can use the fill_value option 
ndf = pd.DataFrame.reindex(df, index = ['first','second', 'third','fourth', 'fifth'], fill_value=10)
ndf

cl1        cl2        cl3        cl4        cl5
first   -0.157623  -1.414416   0.675708   0.549411   1.665969
second  -0.492437   0.685788   0.215040   0.252677  -0.997441
third    0.075487   0.560347  -0.242204  -0.564074   0.122896
fourth   0.466901   0.131506  -1.734850  -2.421723  -0.738227
fifth   10.000000  10.000000  10.000000  10.000000  10.000000

In [64]:
# we can reindex by using the dataframe object too
# we can also change the coloums 
ndf = df.reindex(index = ['first','second', 'third','fourth', 'fifth'], columns = ['cl1', 'cl2', 'cl3','cl4','cl5', 'cl6'], fill_value=10)
ndf

cl1        cl2        cl3        cl4        cl5   cl6
first   -0.157623  -1.414416   0.675708   0.549411   1.665969  10.0
second  -0.492437   0.685788   0.215040   0.252677  -0.997441  10.0
third    0.075487   0.560347  -0.242204  -0.564074   0.122896  10.0
fourth   0.466901   0.131506  -1.734850  -2.421723  -0.738227  10.0
fifth   10.000000  10.000000  10.000000  10.000000  10.000000  10.0

###  more of series 

###  more of dataframe 