In [1]:
import numpy as np
import pandas as pd
import platform
print(platform.python_version())


print(note:= "some basics of numpy before we jump on to pandas")


3.9.0
some basics of numpy before we jump on to pandas


In [2]:
print( note:= "this is python based list")
print()
print( note:= "python list can have diff type of data like string,  int, float, char etc etc etc") 
print()
sample_list = ['a', 1 , 1.2 , '3', 'welcome']

print()
print(note:="we shall see the data as its own type")
print()
print(sample_list)

this is python based list
python list can have diff type of data like string,  int, float, char etc etc etc

we shall see the data as its own type
['a', 1, 1.2, '3', 'welcome']


In [3]:
print(note:='we shall see the data as string type as we have mixed data type')
print()
print(sr := np.array(sample_list))

we shall see the data as string type as we have mixed data type
['a' '1' '1.2' '3' 'welcome']


In [4]:
print(note:= "we can get the dimention of array through shape attribue of arrays")
print()
print(sr.shape) 

we can get the dimention of array through shape attribue of arrays
(5,)


In [5]:
print(note:= "we can get  type of array")
print()
print(sr.dtype)

we can get  type of array
<U7


In [6]:
print(note := "if we use only int data, we shall see the respective in type")
print()
i1r = np.array([1,2,3])
print(i1r.dtype)

if we use only int data, we shall see the respective in type
int64


In [7]:
print(note:= "we can use indexing")
print()
print(i1r[0], i1r[1], i1r[2])

we can use indexing
1 2 3


In [8]:
print(note := "we can create list within list, which is sort of a matrix")
print()
i2r = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i2r.shape)
print(i2r.dtype)

we can create list within list, which is sort of a matrix
(3, 3)
int64


In [9]:
print(note := "we can use indexing")
print(note := "indexing follow the the patterm of range, start is includes, end is not included")
print()
print(i2r[0], i2r[1], i2r[0,1:3], i2r[1,0:2], i2r[1,0:2])
print()
print(i2r[2,:])
print()
print(i2r[:,:])

we can use indexing
 : indexing follow the the patterm of range, start is includes, end is not included
[1 2 3] [4 5 6] [2 3] [4 5] [4 5]

[7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(note := "returns true if any value is true or non-zero")
print()
print(i2r.any())
zero = i2r - i2r 
print(zero.any())

returns true if any value is true or non-zero
True
False


In [11]:
print(note := "returns true if all the values are true or non-zero")
print()
print(i2r.all())
print()
print(note:= "we can do scalar operations on np array")
print()
i2r = i2r - 1
print()
print(i2r.all())

returns true if all the values are true or non-zero
True
we can do scalar operations on np array
False


In [12]:
print(note := "sum returns sum of the array")
print()
print(i2r.sum())

sum returns sum of the array

36


In [13]:
print(note := "we can specify axis information in many of numpy functions")
print()
print(note := " 0 is each coloums") 
print(i2r.sum(0))
print()
print(note := " 1 is rows ")
print(i2r.sum(1))

we can specify axis information in many of numpy functions

 0 is each coloums
[ 9 12 15]

 1 is rows 
[ 3 12 21]


In [14]:
print(note := " we can get mean")
print()
print(i2r.mean())

 we can get mean
4.0


In [15]:
print(note := " mean also supports the axis info")
print()
print(i2r.mean(0))
print()
print(i2r.mean(1))

 mean also supports the axis info
[3. 4. 5.]

[1. 4. 7.]


In [16]:
print(note := " we can also get std ")
print()
print(i2r.std())


 we can also get std 
2.581988897471611


In [17]:
print(note := " std also supports the axis information")
print()
print(i2r.std(0))
print()
print(i2r.std(1))

 std also supports the axis information
[2.44948974 2.44948974 2.44948974]

[0.81649658 0.81649658 0.81649658]


In [18]:
print(note:= "np has arange function to create range of values")
print()
n1r = np.arange(0, 40)
print(n1r)

np has arange function to create range of values
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [19]:
print(note:= "it also has reshape function to shape the values")
print()
n2r = np.arange(0,40,2).reshape(4,5)
print(n2r)

it also has reshape function to shape the values
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [20]:
print(note := " the way you want !!!")
print()
n3r = np.arange(0,40,2).reshape(2,5,2)
print(n3r)

 the way you want !!!
[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]
  [16 18]]

 [[20 22]
  [24 26]
  [28 30]
  [32 34]
  [36 38]]]


In [21]:
print(note := " np also has support to generate random number")
print()
nr = np.random.randn(20).reshape(4,5)
print(nr)

 np also has support to generate random number
[[-1.67115058  0.96496225  0.2466056  -1.8299813   1.94511684]
 [ 0.13767294  0.99608854  2.05523223 -0.35069595 -0.68030287]
 [ 0.0231339   1.11486665 -0.19553908  1.59478897 -1.10120814]
 [ 1.34475786 -0.04549877  2.5800583   0.27733615  0.81811174]]


## PANDAS

### basic of series

In [22]:
print(note := " lets first have a quick look at series")
print()
print(note := " series is like an array but is indexed")
print()
iis = pd.Series([11,12,31,41,15,61,17,80])
print(iis)

 lets first have a quick look at series
 series is like an array but is indexed
0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: int64


In [23]:
print(note := " and unlike numpy we can have mixed data types ")
print()
ms = pd.Series([11,12,'31',41,15,61,'17',80])
print(ms)

 and unlike numpy we can have mixed data types 
0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: object


In [24]:
print(note := " we can get the values")
print(note := " and notice that data still is in original type as passed")
print()
ms.values

 we can get the values
 and notice that data still is in original type as passed


array([11, 12, '31', 41, 15, 61, '17', 80], dtype=object)

In [25]:
print(note := " we can get the indexs")
print(ms.index)
print()
print(note := " index have important role in pandas as we can use them in numerous operations") 
type(ms.index)

 we can get the indexs
RangeIndex(start=0, stop=8, step=1)

 index have important role in pandas as we can use them more numerous operations


pandas.core.indexes.range.RangeIndex

In [114]:
print(note := "we can determine the type of data")
print()
print(iis.dtype)
print(note := " not the type is from numpy class ")
print(note := " pandas uses numpy internally ")
print()
print(type(iis.dtype))
print()
print(ms.dtype)
print()
print(type(ms.dtype))

we can determine the type of data

int64
 not the type is from numpy class 
 pandas uses numpy internally 

<class 'numpy.dtype'>

object

<class 'numpy.dtype'>


In [27]:
print(note := "we can determine the size of data")
print()
ms.size

we can determine the size of data


8

In [115]:
print(note := " or shape ")
print()
ms.shape

 or shape 



(8,)

In [116]:
print(note := "we can get the number of bytes used to store the data ")
print()
print(ms.nbytes)

we can get the number of bytes used to store the data 

64


In [30]:
print(note := " we can use the index to access the values ")
print()
print(ms[5])
print()
print(ms[6])
print()
print(type(ms[5]))
print()
print(type(ms[6]))

 we can use the index to access the values 
61
17
<class 'int'>
<class 'str'>


In [31]:
print(note := " we can also get values based on conditions")
print()
iis[iis > 40]

 we can also get values based on conditions


3    41
5    61
7    80
dtype: int64

In [32]:
print(note := " but this will fail , as str and int can't be compared with >")
print()
#ms[ms>40]

 but this will fail , as str and int can't be compared with >


In [118]:
print(note := " we can use our own indexes rather than using the default index values")
print()
print(note := " here is the number covid cases in million and respective countries as index")
print()
cd = pd.Series([100.3, 80.64, 50.7, 10.83, 10.82], index=['usa','ind','bra','frc','rus'])
print(note := " this is how pandas are beautiful, \
rather than relying on index like in excel we can have representative") 
print()
print(cd)

 we can use our own indexes rather than using the default index values

 here is the number covid cases in million and respective countries as index

 this is how pandas are beautiful, rather than relying on index like in excel we can have representative

usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
dtype: float64


In [34]:
print(note := " we can name our series ")
print()
cd.name = 'covid_cases'
print(note := " we can also name the index")
print()
cd.index.name = 'countries'
cd

 we can name our series 
 we can also name the index


countries
usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
Name: covid_cases, dtype: float64

In [35]:
cd.index

Index(['usa', 'ind', 'bra', 'frc', 'rus'], dtype='object', name='countries')

In [36]:
print(note := " we can check if key exists in index, with in")
print()
'ind' in cd.index

 we can check if key exists in index, with in


True

In [37]:
'chn' in cd.index

False

In [119]:
index_p = cd.index
print(note := " we can get the indexes via int index")
print()
index_p[0]

 we can get the indexes via int index



'usa'

In [39]:
print(note := " this would fail")
print()
print(note := " index are immutable") 
print()
#index_p[0] = 'temp'

 this would fail
 index are immutable


In [40]:
print(note := " we can use the list like slicing ")
print()
index_p[:2]

 we can use the list like slicing 


Index(['usa', 'ind'], dtype='object', name='countries')

In [41]:
index_p[-1]

'rus'

In [42]:
print(note := " what would this print?")
print()
print(note := " index_p[:-1]")

 what would this print?
 index_p[:-1]


In [43]:
print(note := " as index are immutable and can't be changed directly ")
print()
print(note := " we need to use reindex if we want to change them ")
print()
print(note := " if new index is added we shall NaN")
print()
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'])
ncd

 as index are immutable and can't be changed directly 
 we need to use reindex if we want to change them 
 if new index is added we shall NaN


countries
usa    100.30
ind     80.64
frc     10.83
rus     10.82
esp       NaN
bra     50.70
Name: covid_cases, dtype: float64

In [44]:
print(note := " we can use fill_value to specify the default falue if index is not already present")
print()
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'], fill_value='0')
ncd

 we can use fill_value to specify the default falue if index is not already present


countries
usa    100.3
ind    80.64
frc    10.83
rus    10.82
esp        0
bra     50.7
Name: covid_cases, dtype: object

In [45]:
print(note := "we can convert the series to a python dict ")
print()
pcd = ncd.to_dict()
pcd

we can convert the series to a python dict 


{'usa': 100.3,
 'ind': 80.64,
 'frc': 10.83,
 'rus': 10.82,
 'esp': '0',
 'bra': 50.7}

In [120]:
print(note := "we can pass a dict to series to create a series")
print()
bcd = pd.Series(pcd)
print()
print(note := " the extra info that we added like name of index etc will be lost ")
print()
bcd

we can pass a dict to series to create a series


 the extra info that we added like name of index etc will be lost 



usa    100.3
ind    80.64
frc    10.83
rus    10.82
esp        0
bra     50.7
dtype: object

In [47]:
print(note := " we can also specify our own index/keys while passing the dict")
print()
nbcd = pd.Series(pcd, index=['usa','ind','bra','frc','rus','esp','chn'])
nbcd

 we can also specify our own index/keys while passing the dict


usa    100.3
ind    80.64
bra     50.7
frc    10.83
rus    10.82
esp        0
chn      NaN
dtype: object

In [121]:
print(note := " as chn was not part of the dict already we got a new key with NaN value")
print()
print(note := " we can check if we have null values in our series")
print()
pd.isnull(nbcd)

 as chn was not part of the dict already we got a new key with NaN value

 we can check if we have null values in our series



usa    False
ind    False
bra    False
frc    False
rus    False
esp    False
chn     True
dtype: bool

In [122]:
print(note := " we can also use notnull to check what all values are not null in the series")
print()
pd.notnull(nbcd)

 we can also use notnull to check what all values are not null in the series



usa     True
ind     True
bra     True
frc     True
rus     True
esp     True
chn    False
dtype: bool

### basics of dataframe

In [123]:
print(note := " lets first have a quick look at dataframe")
print()
rank_dict = { \
             'year' : [2019,2018,2017,2016,2015], \
             'batsman':['virat kohli', 'virat kohli', 'steve smith', 'steve smith', 'steve smith' ],\
             'batsman country': ['india', 'india', 'australia', 'australia', 'australia'],\
             'bowler': ['Pat Cummins', 'Kagiso Rabada', 'James Anderson', 'James Anderson', 'Ravichandran Ashwin' ],\
            'bowler country':['australia', 'South Africa', 'England', 'India', 'India' ]\
            }
print()
print(note := " we can pass a dict that contains key as the coloum name and list as the respective values ")
print()
icc_ranking = pd.DataFrame(rank_dict)
icc_ranking

 lets first have a quick look at dataframe


 we can pass a dict that contains key as the coloum name and list as the respective values 



year      batsman batsman country               bowler bowler country
0  2019  virat kohli           india          Pat Cummins      australia
1  2018  virat kohli           india        Kagiso Rabada   South Africa
2  2017  steve smith       australia       James Anderson        England
3  2016  steve smith       australia       James Anderson          India
4  2015  steve smith       australia  Ravichandran Ashwin          India

In [51]:
print(note := " pandas automatically adds the indexes as shown above")
print()
print(note := " we can get the coloum names of the dataframe ")
print()
icc_ranking.columns

 pandas automatically adds the indexes as shown above
 we can get the coloum names of the dataframe 


Index(['year', 'batsman', 'batsman country', 'bowler', 'bowler country'], dtype='object')

In [52]:
print(note := " we can also provide index names ")
print()
icc_ranking = pd.DataFrame(rank_dict, index=['19','18','17','16','15'])
icc_ranking

 we can also provide index names 


year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
18  2018  virat kohli           india        Kagiso Rabada   South Africa
17  2017  steve smith       australia       James Anderson        England
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [53]:
print(note := " we can use the coloum names to get the data ")
print()
icc_ranking.year

 we can use the coloum names to get the data 


19    2019
18    2018
17    2017
16    2016
15    2015
Name: year, dtype: int64

In [54]:
print(note := " or we can use ")
print()
icc_ranking['batsman']

 or we can use 


19    virat kohli
18    virat kohli
17    steve smith
16    steve smith
15    steve smith
Name: batsman, dtype: object

In [55]:
print(note := " for column name that has the spaces in middle we have to use the index approach ")
print()
print(note := " so always use index approach ")
print()
icc_ranking['bowler country']

 for column name that has the spaces in middle we have to use the index approach 
 so always use index approach 


19       australia
18    South Africa
17         England
16           India
15           India
Name: bowler country, dtype: object

In [56]:
print(note := " we can also retrive some values from dataframe ")
print()
print(note := " in this case 2 values from the start")
print()
icc_ranking.head(2)

 we can also retrive some values from dataframe 
 in this case 2 values from the start


year      batsman batsman country         bowler bowler country
19  2019  virat kohli           india    Pat Cummins      australia
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [57]:
print(note := " in this case 2 values from the start")
print()
icc_ranking.tail(2)

 in this case 2 values from the start


year      batsman batsman country               bowler bowler country
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [58]:
print(note := " we can also extract data at particular index with the help of iloc")
print()
print(note := " iloc is integer index-based. So here, we have to specify rows and columns by their integer index.")
print()
icc_ranking.iloc[3]

 we can also extract data at particular index with the help of iloc
 iloc is integer index-based. So here, we have to specify rows and columns by their integer index.


year                         2016
batsman               steve smith
batsman country         australia
bowler             James Anderson
bowler country              India
Name: 16, dtype: object

In [59]:
print(note := " we can also select multiple index")
print()
icc_ranking.iloc[[0,2,4]]

 we can also select multiple index


year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
17  2017  steve smith       australia       James Anderson        England
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [60]:
print(note := " we can also select coloums based on index")
print()
icc_ranking.iloc[[0,2,4],[1,2]]

 we can also select coloums based on index


batsman batsman country
19  virat kohli           india
17  steve smith       australia
15  steve smith       australia

In [61]:
print(note := " some notes about iloc vs loc ")
print()
print(note := " On the other hand loc is label-based, which means that we have to specify the name of the rows and ")
print()
print(note := " columns that we need to filter out.")

icc_ranking.loc[icc_ranking['batsman']=='virat kohli']

 some notes about iloc vs loc 
 On the other hand loc is label-based, which means that we have to specify the name of the rows and 
 columns that we need to filter out.


year      batsman batsman country         bowler bowler country
19  2019  virat kohli           india    Pat Cummins      australia
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [62]:
print(note := " we can use & ")
print()
icc_ranking.loc[(icc_ranking['batsman']=='virat kohli') & (icc_ranking['year']==2018)]

 we can use & 


year      batsman batsman country         bowler bowler country
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [63]:
print(note := " we can also filter the coloums to be printed ")
print()
icc_ranking.loc[icc_ranking['year'] >= 2017, ['batsman', 'batsman country']]

 we can also filter the coloums to be printed 


batsman batsman country
19  virat kohli           india
18  virat kohli           india
17  steve smith       australia

In [64]:
print(note := " we can also extract multiple columns from the data frame")
print()
print(note := " this basically creates a new dataframe with selected coloums")
print()
pd.DataFrame(icc_ranking, columns=['year', 'batsman', 'batsman country'])

 we can also extract multiple columns from the data frame
 this basically creates a new dataframe with selected coloums


year      batsman batsman country
19  2019  virat kohli           india
18  2018  virat kohli           india
17  2017  steve smith       australia
16  2016  steve smith       australia
15  2015  steve smith       australia

In [65]:
print(note := " we can also extract multiple columns from the data frame")
print()
print(note := " if we pass a coloum name that does not exists we shall get NaN values")
print()
pd.DataFrame(icc_ranking, columns=['year', 'bowler', 'bowler country', 'notdefined'])

 we can also extract multiple columns from the data frame
 if we pass a coloum name that does not exists we shall get NaN values


year               bowler bowler country  notdefined
19  2019          Pat Cummins      australia         NaN
18  2018        Kagiso Rabada   South Africa         NaN
17  2017       James Anderson        England         NaN
16  2016       James Anderson          India         NaN
15  2015  Ravichandran Ashwin          India         NaN

In [66]:
print(note := " let us create a Dataframe from numbers and provide user defined index and coloum names")
print()
df = pd.DataFrame(np.random.randn(20).reshape(4,5), index = ['first','second', 'third','fourth'], 
                  columns=['cl1', 'cl2', 'cl3','cl4','cl5'])
df

 let us create a Dataframe from numbers and provide user defined index and coloum names


cl1       cl2       cl3       cl4       cl5
first  -1.382272 -0.286808  0.503992 -1.352474 -0.535485
second  0.343436  0.198736 -0.009042  0.899137  0.924316
third   0.909569 -0.535093 -2.672892 -1.813985 -2.176855
fourth  0.214363  0.364521  0.588193 -0.492224  2.099656

In [67]:
print(note := " we can reindex the DataFrame")
print()
print(note := " and can use the fill_value option ")
print()
ndf = pd.DataFrame.reindex(df, index = ['first','second', 'third','fourth', 'fifth'], fill_value=10)
ndf

 we can reindex the DataFrame
 and can use the fill_value option 


cl1        cl2        cl3        cl4        cl5
first   -1.382272  -0.286808   0.503992  -1.352474  -0.535485
second   0.343436   0.198736  -0.009042   0.899137   0.924316
third    0.909569  -0.535093  -2.672892  -1.813985  -2.176855
fourth   0.214363   0.364521   0.588193  -0.492224   2.099656
fifth   10.000000  10.000000  10.000000  10.000000  10.000000

In [68]:
print(note := " we can reindex by using the dataframe object too")
print()
print(note := " we can also change the coloums ")
print()
ndf = df.reindex(index = ['first','second', 'third','fourth', 'fifth'], columns = ['cl1', 'cl2', 'cl3','cl4','cl5', 'cl6'], fill_value=10)
ndf

 we can reindex by using the dataframe object too
 we can also change the coloums 


cl1        cl2        cl3        cl4        cl5   cl6
first   -1.382272  -0.286808   0.503992  -1.352474  -0.535485  10.0
second   0.343436   0.198736  -0.009042   0.899137   0.924316  10.0
third    0.909569  -0.535093  -2.672892  -1.813985  -2.176855  10.0
fourth   0.214363   0.364521   0.588193  -0.492224   2.099656  10.0
fifth   10.000000  10.000000  10.000000  10.000000  10.000000  10.0

### more of series 

In [69]:
some_series = pd.Series(np.random.rand(5), index=['a','c','d','e','b'])
some_series

a    0.910548
c    0.032130
d    0.514590
e    0.789566
b    0.897456
dtype: float64

In [70]:
some_series[some_series>.5]

a    0.910548
d    0.514590
e    0.789566
b    0.897456
dtype: float64

In [71]:
print(note := " we can update a value in the series")
print()
some_series[some_series>.5] = 1
some_series

 we can update a value in the series


a    1.00000
c    0.03213
d    1.00000
e    1.00000
b    1.00000
dtype: float64

In [72]:
some_series[['a','d']]


a    1.0
d    1.0
dtype: float64

In [73]:
some_series[[0,3]]

a    1.0
e    1.0
dtype: float64

In [74]:
print(note := " we can sort the index of the series")
print()
some_series = some_series.sort_index()
some_series

 we can sort the index of the series


a    1.00000
b    1.00000
c    0.03213
d    1.00000
e    1.00000
dtype: float64

In [75]:
print(note := " we can also sort the series based on the values")
print()
some_series.sort_values()

 we can also sort the series based on the values


c    0.03213
a    1.00000
b    1.00000
d    1.00000
e    1.00000
dtype: float64

In [76]:
print(note := "we can use rank to get the ranking of values, showing the order of values ")
print()
print(note := " when we run sort etc, we shall have the values in order of rank")
print()
some_series.rank()

we can use rank to get the ranking of values, showing the order of values 
 when we run sort etc, we shall have the values in order of rank


a    3.5
b    3.5
c    1.0
d    3.5
e    3.5
dtype: float64

In [77]:
print(note := " we can also sort them in ascending order")
print()
some_series.sort_values(ascending=True)

 we can also sort them in ascending order


c    0.03213
a    1.00000
b    1.00000
d    1.00000
e    1.00000
dtype: float64

In [78]:
print(note := " we can use drop to remove a value from the series, remember that new series is created ")
print()
nss = some_series.drop('c')
nss

 we can use drop to remove a value from the series, remember that new series is created 


a    1.0
b    1.0
d    1.0
e    1.0
dtype: float64

In [79]:
some_series_1 = pd.Series(np.random.rand(6), index=['a','b','c','d','e','f'])
print()
some_series_1

a    0.061675
b    0.666872
c    0.306409
d    0.409942
e    0.451962
f    0.234448
dtype: float64

In [80]:
print(note := " we can do scalar operation on the series ")
print()
some_series_2 = some_series_1*2
some_series_2

 we can do scalar operation on the series 


a    0.123349
b    1.333744
c    0.612817
d    0.819883
e    0.903924
f    0.468897
dtype: float64

In [81]:
some_series_2 = some_series_2 - 1
some_series_2

a   -0.876651
b    0.333744
c   -0.387183
d   -0.180117
e   -0.096076
f   -0.531103
dtype: float64

In [82]:
print(note := " we can add two series ")
print()
some_series_2 + some_series_1

 we can add two series 


a   -0.814976
b    1.000616
c   -0.080774
d    0.229825
e    0.355887
f   -0.296655
dtype: float64

In [83]:
print(note := " but only when we have same index names can we see the result, else we shall see NaN")
print()
some_series + some_series_2

 but only when we have same index names can we see the result, else we shall see NaN


a    0.123349
b    1.333744
c   -0.355053
d    0.819883
e    0.903924
f         NaN
dtype: float64

In [84]:
print(note := " we can use the pct_chnage to get the percentage change between series values")
print()
new_s = some_series.pct_change()
new_s

 we can use the pct_chnage to get the percentage change between series values


a          NaN
b     0.000000
c    -0.967870
d    30.123624
e     0.000000
dtype: float64

In [85]:
print(note := " we can use isnull to get the NaN values ")
print()
new_s.isnull()

 we can use isnull to get the NaN values 


a     True
b    False
c    False
d    False
e    False
dtype: bool

In [86]:
print(note := " we can directly drop the Nan values by dropna")
print()
new_s = new_s.dropna()
new_s

 we can directly drop the Nan values by dropna


b     0.000000
c    -0.967870
d    30.123624
e     0.000000
dtype: float64

In [87]:
new_s.min()

-0.9678700652730327

In [88]:
new_s.max()

30.1236237638752

In [89]:
new_s.std()

15.229959375053827

In [90]:
new_s.mean()

7.288938424650542

In [91]:
print(note := " series supports describe that can be used to get some basic stats of data")
print()
new_s.describe()

 series supports describe that can be used to get some basic stats of data


count     4.000000
mean      7.288938
std      15.229959
min      -0.967870
25%      -0.241968
50%       0.000000
75%       7.530906
max      30.123624
dtype: float64

### more of dataframe 

In [92]:
some_df = pd.DataFrame(np.random.rand(20).reshape(4,5), index=['a','b','c','d'], columns=['c1','c2','c3','c4','c5'])
some_df

c1        c2        c3        c4        c5
a  0.774619  0.236447  0.879229  0.073653  0.724922
b  0.931094  0.595232  0.048746  0.001396  0.206756
c  0.339759  0.788861  0.371098  0.635688  0.235639
d  0.305573  0.239135  0.185057  0.968995  0.538801

In [93]:
print(note := " axis value is 0 for row, i.e. the default behaviour")
print()
some_df.drop('a', axis=0)

 axis value is 0 for row, i.e. the default behaviour


c1        c2        c3        c4        c5
b  0.931094  0.595232  0.048746  0.001396  0.206756
c  0.339759  0.788861  0.371098  0.635688  0.235639
d  0.305573  0.239135  0.185057  0.968995  0.538801

In [94]:
some_df.drop('c3', axis=1)

c1        c2        c4        c5
a  0.774619  0.236447  0.073653  0.724922
b  0.931094  0.595232  0.001396  0.206756
c  0.339759  0.788861  0.635688  0.235639
d  0.305573  0.239135  0.968995  0.538801

In [95]:
print(note := " we can select the data by col index")
print()
some_df['c1']

 we can select the data by col index


a    0.774619
b    0.931094
c    0.339759
d    0.305573
Name: c1, dtype: float64

In [96]:
print(note := " we can use the condition to select relevant data")
print()
some_df[some_df['c3']>.5]

 we can use the condition to select relevant data


c1        c2        c3        c4        c5
a  0.774619  0.236447  0.879229  0.073653  0.724922

In [97]:
print(note := " which is same as using loc")
print()
some_df.loc[some_df['c3']>.5]

 which is same as using loc


c1        c2        c3        c4        c5
a  0.774619  0.236447  0.879229  0.073653  0.724922

In [98]:
print(note := " we can also do conditional on the entire dataframe")
print()
some_df > .2

 we can also do conditional on the entire dataframe


c1    c2     c3     c4    c5
a  True  True   True  False  True
b  True  True  False  False  True
c  True  True   True   True  True
d  True  True  False   True  True

In [99]:
print(note := " we can do the scalar operation on the dataframe")
print()
some_df_1 = some_df + 1
some_df_1

 we can do the scalar operation on the dataframe


c1        c2        c3        c4        c5
a  1.774619  1.236447  1.879229  1.073653  1.724922
b  1.931094  1.595232  1.048746  1.001396  1.206756
c  1.339759  1.788861  1.371098  1.635688  1.235639
d  1.305573  1.239135  1.185057  1.968995  1.538801

In [100]:
print(note := " we can add two dataframes")
print()
some_df_2 = some_df_1 + some_df
some_df_2

 we can add two dataframes


c1        c2        c3        c4        c5
a  2.549239  1.472894  2.758458  1.147306  2.449843
b  2.862187  2.190463  1.097492  1.002791  1.413511
c  1.679519  2.577722  1.742195  2.271375  1.471278
d  1.611145  1.478269  1.370113  2.937990  2.077601

In [101]:
print(note := " if the row/col numners doesnt match than we shall see the NaN")
print(note := " subset of row/col data shall be shown ") 
print()
some_df_2 + some_df[some_df['c3']>.5]

 if the row/col numners doesnt match than we shall see the NaN
 subset of row/col data shall be shown 


c1        c2        c3        c4        c5
a  3.323858  1.709342  3.637687  1.220959  3.174765
b       NaN       NaN       NaN       NaN       NaN
c       NaN       NaN       NaN       NaN       NaN
d       NaN       NaN       NaN       NaN       NaN

In [102]:
print(note := "we can use the add function to fill some value instread of NaN")
print()
some_df_2.add(some_df[some_df['c3']>.5], fill_value='0')

we can use the add function to fill some value instread of NaN


c1        c2        c3        c4        c5
a  3.323858  1.709342  3.637687  1.220959  3.174765
b  2.862187  2.190463  1.097492  1.002791  1.413511
c  1.679519  2.577722  1.742195  2.271375  1.471278
d  1.611145  1.478269  1.370113  2.937990  2.077601

In [103]:
print(note := "we can use the loc to get the particular row")
print()
x = some_df_2.loc['a']
x

we can use the loc to get the particular row


c1    2.549239
c2    1.472894
c3    2.758458
c4    1.147306
c5    2.449843
Name: a, dtype: float64

In [104]:
print(note := "we can do operation like addition, substraction etc between dataFrame and Series")
print()
print(note := "the value of series shall be deducted from every row")
print()
some_df_2 - x

we can do operation like addition, substraction etc between dataFrame and Series
the value of series shall be deducted from every row


c1        c2        c3        c4        c5
a  0.000000  0.000000  0.000000  0.000000  0.000000
b  0.312949  0.717569 -1.660966 -0.144515 -1.036332
c -0.869720  1.104827 -1.016263  1.124069 -0.978565
d -0.938094  0.005375 -1.388345  1.790684 -0.372242

In [105]:
new_df = pd.DataFrame(np.arange(30).reshape(6,5), index=['a','b','c','d','e','f'], columns=['c1','c2','c3','c4','c5'])
new_df

c1  c2  c3  c4  c5
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29

In [106]:
print(note := "pandas supports sum operation")
print(note := "default behaviour is to sum all the cols")
print()
new_df.sum()

pandas supports sum operation
default behaviour is to sum all the cols


c1    75
c2    81
c3    87
c4    93
c5    99
dtype: int64

In [107]:
print(note := "we can specify the axis as 1 to do sum based on rows")
print()
new_df.sum(axis=1)

we can specify the axis as 1 to do sum based on rows


a     10
b     35
c     60
d     85
e    110
f    135
dtype: int64

In [108]:
print(note := "we can pass the axis to get min of each row, here we using default")
print()
new_df.min()

we can pass the axis to get min of each row, here we using default


c1    0
c2    1
c3    2
c4    3
c5    4
dtype: int64

In [109]:
print(note := "we can also get the max values")
print()
new_df.max(axis=1)

we can also get the max values


a     4
b     9
c    14
d    19
e    24
f    29
dtype: int64

In [110]:
print(note := "we can get the index information for the minimum value")
print()
new_df.idxmin()

we can get the index information for the minimum value


c1    a
c2    a
c3    a
c4    a
c5    a
dtype: object

In [111]:
print(note := "we can get the index information for the max values")
print()
new_df.idxmax(axis=1)

we can get the index information for the max values


a    c5
b    c5
c    c5
d    c5
e    c5
f    c5
dtype: object

In [112]:
new_df.std()

c1    9.354143
c2    9.354143
c3    9.354143
c4    9.354143
c5    9.354143
dtype: float64

In [113]:
print(note := "pandas also has a descrive function, which shows us some basic statistic information about the dataframe")
print()
new_df.describe()

pandas also has a descrive function, which shows us some basic statistic information about the dataframe


c1         c2         c3         c4         c5
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   12.500000  13.500000  14.500000  15.500000  16.500000
std     9.354143   9.354143   9.354143   9.354143   9.354143
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     6.250000   7.250000   8.250000   9.250000  10.250000
50%    12.500000  13.500000  14.500000  15.500000  16.500000
75%    18.750000  19.750000  20.750000  21.750000  22.750000
max    25.000000  26.000000  27.000000  28.000000  29.000000

# That's all folks !!!

In [ ]:
print(note := "we started with numpy basics")
print(note := "we learned about pandas dataframe and pandas series")
print(note := "in next session we will work on ukbb csv data and apply our learning from this session")