In [1]:
import numpy as np
import pandas as pd
import platform
print(platform.python_version())

print(note:="Hello World!!")



3.9.0
Hello World!!


In [2]:
print(note:= "some basics of numpy before we jump on to pandas")
print()
print( note:= "this is python based list")
print()
print( note:= "python list can have diff type of data like string,  int, float, char etc etc etc") 
print()
sample_list = ['a', 1 , 1.2 , '3', 'welcome']

print()
print(note:="we shall see the data as its own type")
print()
print(sample_list)

some basics of numpy before we jump on to pandas

this is python based list

python list can have diff type of data like string,  int, float, char etc etc etc


we shall see the data as its own type

['a', 1, 1.2, '3', 'welcome']


In [3]:
print(note:='we shall see the data as string type as we have mixed data type')
print()
print(sr := np.array(sample_list))

we shall see the data as string type as we have mixed data type

['a' '1' '1.2' '3' 'welcome']


In [4]:
print(note:= "we can get the dimention of array through shape attribue of arrays")
print()
print(sr.shape) 

we can get the dimention of array through shape attribue of arrays

(5,)


In [5]:
print(note:= "we can get  type of array")
print()
print(sr.dtype)

we can get  type of array

<U7


In [6]:
print(note := "if we use only int data, we shall see the respective in type")
print()
i1r = np.array([1,2,3])
print(i1r.dtype)

if we use only int data, we shall see the respective in type

int64


In [7]:
print(note:= "we can use indexing")
print()
print(i1r[0], i1r[1], i1r[2])

we can use indexing

1 2 3


In [8]:
print(note := "we can create list within list, which is sort of a matrix")
print()
i2r = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i2r.shape)
print(i2r.dtype)
print(i2r)

we can create list within list, which is sort of a matrix

(3, 3)
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(note := "we can use indexing")
print(note := "indexing follow the the patterm of range, start is includes, end is not included")
print()
print(i2r[0], i2r[1], i2r[0,1:3], i2r[1,0:2], i2r[1,0:2])
print()
print(i2r[2,:])
print()
print(i2r[:,:])

we can use indexing
indexing follow the the patterm of range, start is includes, end is not included

[1 2 3] [4 5 6] [2 3] [4 5] [4 5]

[7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(note := "returns true if any value is true or non-zero")
print()
print(i2r.any())
# yes we can do this!!!
zero = i2r - i2r 
print(zero)
print(zero.any())

returns true if any value is true or non-zero

True
[[0 0 0]
 [0 0 0]
 [0 0 0]]
False


In [11]:
print(note := "returns true if all the values are true or non-zero")
print()
print(i2r.all())
print()
print(note:= "we can do scalar operations on np array")
print()
i2r = i2r - 1
print(i2r)
print()
print(i2r.all())

returns true if all the values are true or non-zero

True

we can do scalar operations on np array

[[0 1 2]
 [3 4 5]
 [6 7 8]]

False


In [12]:
print(note := "sum returns sum of the array")
print()
print(i2r.sum())

sum returns sum of the array

36


In [13]:
print(note := "we can specify axis information in many of numpy functions")
print()
print(note := " 0 is each coloums or rather think it as vertically") 
print(i2r.sum(0))
print()
print(note := " 1 is rows or horizontally ")
print(i2r.sum(1))

we can specify axis information in many of numpy functions

 0 is each coloums or rather think it as vertically
[ 9 12 15]

 1 is rows or horizontally 
[ 3 12 21]


In [14]:
print(note := " we can get mean")
print()
print(i2r.mean())

 we can get mean

4.0


In [15]:
print(note := " mean also supports the axis info")
print()
print(i2r.mean(0))
print()
print(i2r.mean(1))

 mean also supports the axis info

[3. 4. 5.]

[1. 4. 7.]


In [16]:
print(note := " we can also get std ")
print()
print(i2r.std())


 we can also get std 

2.581988897471611


In [17]:
print(note := " std also supports the axis information")
print()
print(i2r.std(0))
print()
print(i2r.std(1))

 std also supports the axis information

[2.44948974 2.44948974 2.44948974]

[0.81649658 0.81649658 0.81649658]


In [18]:
print(note:= "np has arange function to create range of values")
print()
n1r = np.arange(0, 40)
print(n1r)

np has arange function to create range of values

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [19]:
print(note:= "it also has reshape function to shape the values")
print()
n2r = np.arange(0,40,2).reshape(4,5)
print(n2r)
print()
print(n2r.shape)

it also has reshape function to shape the values

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]

(4, 5)


In [20]:
print(note := " the way you want !!!")
print()
n3r = np.arange(0,40,2).reshape(2,5,2)
print(n3r)
print()
print(n3r.shape)

 the way you want !!!

[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]
  [16 18]]

 [[20 22]
  [24 26]
  [28 30]
  [32 34]
  [36 38]]]

(2, 5, 2)


In [21]:
print(note := " np also has support to generate random number")
print()
nr = np.random.randn(20).reshape(4,5)
print(nr)

 np also has support to generate random number

[[-0.68562387 -1.15823426  0.76260418  0.7761207   0.2978953 ]
 [-1.56064734  0.88016895  0.43124183  0.64368166 -1.52337668]
 [ 1.32334115 -1.15384297 -0.984344   -0.73516649 -1.42778394]
 [-2.45565687 -0.56100151 -0.31943153 -0.39264889 -1.08490498]]


## PANDAS

### basic of series

In [22]:
print(note := " lets first have a quick look at series")
print()
print(note := " series is like an array but is indexed")
print()
iis = pd.Series([11,12,31,41,15,61,17,80])
print(iis)

 lets first have a quick look at series

 series is like an array but is indexed

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: int64


In [23]:
print(note := " and unlike numpy we can have mixed data types ")
print()
ms = pd.Series([11,12,'31',41,15,61,'17',80])
print(ms)

 and unlike numpy we can have mixed data types 

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: object


In [24]:
print(note := " we can get the values")
print(note := " and notice that data still is in original type as passed")
print()
ms.values

 we can get the values
 and notice that data still is in original type as passed



array([11, 12, '31', 41, 15, 61, '17', 80], dtype=object)

In [25]:
print(note := " we can get the indexs")
print(ms.index)
print()
print(note := " index have important role in pandas as we can use them in numerous operations") 
type(ms.index)

 we can get the indexs
RangeIndex(start=0, stop=8, step=1)

 index have important role in pandas as we can use them in numerous operations


pandas.core.indexes.range.RangeIndex

In [26]:
print(note := "we can determine the type of data")
print()
print(iis.dtype)
print(note := " not the type is from numpy class ")
print(note := " pandas uses numpy internally ")
print()
print(type(iis.dtype))
print()
print(ms.dtype)
print()
print(type(ms.dtype))

we can determine the type of data

int64
 not the type is from numpy class 
 pandas uses numpy internally 

<class 'numpy.dtype'>

object

<class 'numpy.dtype'>


In [27]:
print(note := "we can determine the size of data")
print()
ms.size

we can determine the size of data



8

In [28]:
print(note := " or shape ")
print()
ms.shape

 or shape 



(8,)

In [29]:
print(note := "we can get the number of bytes used to store the data ")
print()
print(ms.nbytes)

we can get the number of bytes used to store the data 

64


In [30]:
print(note := " we can use the index to access the values ")
print()
print(ms)
print(ms[5])
print()
print(ms[6])
print()
print(type(ms[5]))
print()
print(type(ms[6]))

 we can use the index to access the values 

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: object
61

17

<class 'int'>

<class 'str'>


In [31]:
print(note := " we can also get values based on conditions")
print()
print(iis)
iis[iis > 40]

 we can also get values based on conditions

0    11
1    12
2    31
3    41
4    15
5    61
6    17
7    80
dtype: int64


3    41
5    61
7    80
dtype: int64

In [32]:
print(note := " but this will fail , as str and int can't be compared with >")
print()
#ms[ms>40]

 but this will fail , as str and int can't be compared with >



In [33]:
print(note := " we can use our own indexes rather than using the default index values")
print()
print(note := " here is the number covid cases in million and respective countries as index")
print()
cd = pd.Series([100.3, 80.64, 50.7, 10.83, 10.82], index=['usa','ind','bra','frc','rus'])
print(note := " this is how pandas are beautiful, \
rather than relying on index like in excel we can have representative") 
print()
print(cd)

 we can use our own indexes rather than using the default index values

 here is the number covid cases in million and respective countries as index

 this is how pandas are beautiful, rather than relying on index like in excel we can have representative

usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
dtype: float64


In [34]:
print(note := " we can name our series ")
print()
cd.name = 'covid_cases'
print(note := " we can also name the index")
print()
cd.index.name = 'countries'
cd

 we can name our series 

 we can also name the index



countries
usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
Name: covid_cases, dtype: float64

In [35]:
cd.index

Index(['usa', 'ind', 'bra', 'frc', 'rus'], dtype='object', name='countries')

In [36]:
print(note := " we can check if key exists in index, with in")
print()
'ind' in cd.index

 we can check if key exists in index, with in



True

In [37]:
'chn' in cd.index

False

In [38]:
index_p = cd.index
print(note := " we can get the indexes via int index")
print()
print(index_p[0])
print(cd[0])

 we can get the indexes via int index

usa
100.3


In [39]:
print(note := " this would fail")
print()
print(note := " index are immutable") 
print()
#index_p[0] = 'temp'

 this would fail

 index are immutable



In [40]:
print(note := " we can use the list like slicing ")
print()
index_p[:2]

 we can use the list like slicing 



Index(['usa', 'ind'], dtype='object', name='countries')

In [41]:
index_p[-1]

'rus'

In [42]:
print(note := " what would this print?")
print(index_p)
print()
index_p[:-2]

 what would this print?
Index(['usa', 'ind', 'bra', 'frc', 'rus'], dtype='object', name='countries')



Index(['usa', 'ind', 'bra'], dtype='object', name='countries')

In [43]:
print(note := " as index are immutable and order can't be changed directly ")
print()
print(note := " we need to use reindex if we want to change them ")
print()
print(cd)
print(note := " if new index is added we shall NaN")
print()
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'])
ncd

 as index are immutable and order can't be changed directly 

 we need to use reindex if we want to change them 

countries
usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
Name: covid_cases, dtype: float64
 if new index is added we shall NaN



countries
usa    100.30
ind     80.64
frc     10.83
rus     10.82
esp       NaN
bra     50.70
Name: covid_cases, dtype: float64

In [44]:
print(note := " we can use fill_value to specify the default falue if index is not already present")
print()
ncd = cd.reindex(['usa','ind','frc', 'rus', 'esp', 'bra'], fill_value=0)
ncd

 we can use fill_value to specify the default falue if index is not already present



countries
usa    100.30
ind     80.64
frc     10.83
rus     10.82
esp      0.00
bra     50.70
Name: covid_cases, dtype: float64

In [45]:
print(note := "we can convert the series to a python dict ")
print()
pcd = ncd.to_dict()
pcd

we can convert the series to a python dict 



{'usa': 100.3,
 'ind': 80.64,
 'frc': 10.83,
 'rus': 10.82,
 'esp': 0.0,
 'bra': 50.7}

In [46]:
print(note := "we can pass a dict to series to create a series")
print()
bcd = pd.Series(pcd)
print()
print(note := " the extra info that we added like name of index etc will be lost ")
print()
bcd

we can pass a dict to series to create a series


 the extra info that we added like name of index etc will be lost 



usa    100.30
ind     80.64
frc     10.83
rus     10.82
esp      0.00
bra     50.70
dtype: float64

In [47]:
print(note := " we can also specify our own index/keys while passing the dict")
print()
print(pcd)
nbcd = pd.Series(pcd, index=['usa','ind','bra','frc','rus','esp','chn'])
nbcd

 we can also specify our own index/keys while passing the dict

{'usa': 100.3, 'ind': 80.64, 'frc': 10.83, 'rus': 10.82, 'esp': 0.0, 'bra': 50.7}


usa    100.30
ind     80.64
bra     50.70
frc     10.83
rus     10.82
esp      0.00
chn       NaN
dtype: float64

In [48]:
print(note := " as chn was not part of the dict already we got a new key with NaN value")
print()
print(note := " we can check if we have NaN values in our series")
print()
pd.isnull(nbcd)

 as chn was not part of the dict already we got a new key with NaN value

 we can check if we have NaN values in our series



usa    False
ind    False
bra    False
frc    False
rus    False
esp    False
chn     True
dtype: bool

In [49]:
print(note := " we can also use notnull to check what all values are not NaN in the series")
print()
pd.notnull(nbcd)

 we can also use notnull to check what all values are not NaN in the series



usa     True
ind     True
bra     True
frc     True
rus     True
esp     True
chn    False
dtype: bool

### basics of dataframe

In [50]:
print(note := " lets first have a quick look at dataframe")
print()
rank_dict = { \
             'year' : [2019,2018,2017,2016,2015], \
             'batsman':['virat kohli', 'virat kohli', 'steve smith', 'steve smith', 'steve smith' ],\
             'batsman country': ['india', 'india', 'australia', 'australia', 'australia'],\
             'bowler': ['Pat Cummins', 'Kagiso Rabada', 'James Anderson', 'James Anderson', 'Ravichandran Ashwin' ],\
            'bowler country':['australia', 'South Africa', 'England', 'India', 'India' ]\
            }
print()
print(note := " we can pass a dict that contains key as the coloum name and list as the respective values ")
print()
icc_ranking = pd.DataFrame(rank_dict)
icc_ranking

 lets first have a quick look at dataframe


 we can pass a dict that contains key as the coloum name and list as the respective values 



year      batsman batsman country               bowler bowler country
0  2019  virat kohli           india          Pat Cummins      australia
1  2018  virat kohli           india        Kagiso Rabada   South Africa
2  2017  steve smith       australia       James Anderson        England
3  2016  steve smith       australia       James Anderson          India
4  2015  steve smith       australia  Ravichandran Ashwin          India

In [51]:
print(note := " pandas automatically adds the indexes as shown above")
print()
print(note := " we can get the coloum names of the dataframe ")
print()
print(icc_ranking.columns)

 pandas automatically adds the indexes as shown above

 we can get the coloum names of the dataframe 

Index(['year', 'batsman', 'batsman country', 'bowler', 'bowler country'], dtype='object')


In [52]:
print(note := " we can also provide index names ")
print()
icc_ranking = pd.DataFrame(rank_dict, index=['19','18','17','16','15'])
icc_ranking

 we can also provide index names 



year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
18  2018  virat kohli           india        Kagiso Rabada   South Africa
17  2017  steve smith       australia       James Anderson        England
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [53]:
print(note := " we can use the coloum names to get the data ")
print()
icc_ranking.year

 we can use the coloum names to get the data 



19    2019
18    2018
17    2017
16    2016
15    2015
Name: year, dtype: int64

In [54]:
print(note := " or we can use ")
print()
icc_ranking['batsman']

 or we can use 



19    virat kohli
18    virat kohli
17    steve smith
16    steve smith
15    steve smith
Name: batsman, dtype: object

In [55]:
print(note := " for column name that has the spaces in middle we have to use the index approach ")
print()
print(note := " so always use index approach ")
print()
icc_ranking['bowler country']

 for column name that has the spaces in middle we have to use the index approach 

 so always use index approach 



19       australia
18    South Africa
17         England
16           India
15           India
Name: bowler country, dtype: object

In [56]:
print(note := " we can also retrive some values from dataframe ")
print()
print(note := " in this case 2 values from the start")
print()
icc_ranking.head(2)

 we can also retrive some values from dataframe 

 in this case 2 values from the start



year      batsman batsman country         bowler bowler country
19  2019  virat kohli           india    Pat Cummins      australia
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [57]:
print(note := " in this case 2 values from the start")
print()
icc_ranking.tail(2)

 in this case 2 values from the start



year      batsman batsman country               bowler bowler country
16  2016  steve smith       australia       James Anderson          India
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [58]:
print(note := " we can also extract data at particular index with the help of iloc")
print()
print(note := " iloc is integer index-based. So here, we have to specify rows and columns by their integer index.")
print()
icc_ranking.iloc[3]

 we can also extract data at particular index with the help of iloc

 iloc is integer index-based. So here, we have to specify rows and columns by their integer index.



year                         2016
batsman               steve smith
batsman country         australia
bowler             James Anderson
bowler country              India
Name: 16, dtype: object

In [59]:
print(note := " we can also select multiple index")
print()
icc_ranking.iloc[[0,2,4]]

 we can also select multiple index



year      batsman batsman country               bowler bowler country
19  2019  virat kohli           india          Pat Cummins      australia
17  2017  steve smith       australia       James Anderson        England
15  2015  steve smith       australia  Ravichandran Ashwin          India

In [60]:
print(note := " we can also select coloums based on index")
print()
icc_ranking.iloc[[0,2,4],[1,2]]

 we can also select coloums based on index



batsman batsman country
19  virat kohli           india
17  steve smith       australia
15  steve smith       australia

In [61]:

print(note := " On the other hand loc is label-based, which means that we have to specify the name of the rows and ")
print()
print(note := " columns that we need to filter out.")

icc_ranking.loc[icc_ranking['batsman']=='virat kohli']

 On the other hand loc is label-based, which means that we have to specify the name of the rows and 

 columns that we need to filter out.


year      batsman batsman country         bowler bowler country
19  2019  virat kohli           india    Pat Cummins      australia
18  2018  virat kohli           india  Kagiso Rabada   South Africa

In [62]:
print(note := " we can use & ")
print()
DATA = icc_ranking.loc[(icc_ranking['batsman']=='virat kohli') & (icc_ranking['year']==2018)]
print(DATA)
print(type(DATA))

 we can use & 

    year      batsman batsman country         bowler bowler country
18  2018  virat kohli           india  Kagiso Rabada   South Africa
<class 'pandas.core.frame.DataFrame'>


In [63]:
print(note := " we can also filter the coloums to be printed ")
print()
icc_ranking.loc[icc_ranking['year'] >= 2017, ['batsman', 'batsman country']]

 we can also filter the coloums to be printed 



batsman batsman country
19  virat kohli           india
18  virat kohli           india
17  steve smith       australia

In [64]:
print(note := " we can also extract multiple columns from the data frame")
print()
print(note := " this basically creates a new dataframe with selected coloums")
print()
pd.DataFrame(icc_ranking, columns=['year', 'batsman', 'batsman country'])

 we can also extract multiple columns from the data frame

 this basically creates a new dataframe with selected coloums



year      batsman batsman country
19  2019  virat kohli           india
18  2018  virat kohli           india
17  2017  steve smith       australia
16  2016  steve smith       australia
15  2015  steve smith       australia

In [65]:
print(note := " we can also extract multiple columns from the data frame")
print()
print(note := " if we pass a coloum name that does not exists we shall get NaN values")
print()
pd.DataFrame(icc_ranking, columns=['year', 'bowler', 'bowler country', 'notdefined'])

 we can also extract multiple columns from the data frame

 if we pass a coloum name that does not exists we shall get NaN values



year               bowler bowler country  notdefined
19  2019          Pat Cummins      australia         NaN
18  2018        Kagiso Rabada   South Africa         NaN
17  2017       James Anderson        England         NaN
16  2016       James Anderson          India         NaN
15  2015  Ravichandran Ashwin          India         NaN

In [66]:
print(note := " let us create a Dataframe from numbers and provide user defined index and coloum names")
print()
df = pd.DataFrame(np.random.randn(20).reshape(4,5), index = ['first','second', 'third','fourth'], 
                  columns=['cl1', 'cl2', 'cl3','cl4','cl5'])
df

 let us create a Dataframe from numbers and provide user defined index and coloum names



cl1       cl2       cl3       cl4       cl5
first   0.564205  0.618080 -1.019594  1.382745  1.109097
second  0.961304  0.953810 -1.255732 -0.526440  0.265839
third   0.877244 -3.066932 -1.739485 -0.708067 -0.295822
fourth  0.669795 -0.279458 -0.560824  1.053760  0.836211

In [67]:
print(note := " we can reindex the DataFrame")
print()
print(note := " and can use the fill_value option ")
print()
ndf = pd.DataFrame.reindex(df, index = ['first','second', 'third','fourth', 'fifth'], fill_value=10)
ndf

 we can reindex the DataFrame

 and can use the fill_value option 



cl1        cl2        cl3        cl4        cl5
first    0.564205   0.618080  -1.019594   1.382745   1.109097
second   0.961304   0.953810  -1.255732  -0.526440   0.265839
third    0.877244  -3.066932  -1.739485  -0.708067  -0.295822
fourth   0.669795  -0.279458  -0.560824   1.053760   0.836211
fifth   10.000000  10.000000  10.000000  10.000000  10.000000

In [68]:
print(note := " we can reindex by using the dataframe object too")
print()
print(note := " we can also change the coloums ")
print()
ndf = df.reindex(index = ['first','second', 'third','fourth', 'fifth'], columns = ['cl1', 'cl2', 'cl3','cl4','cl5', 'cl6'], fill_value=10)
ndf

 we can reindex by using the dataframe object too

 we can also change the coloums 



cl1        cl2        cl3        cl4        cl5   cl6
first    0.564205   0.618080  -1.019594   1.382745   1.109097  10.0
second   0.961304   0.953810  -1.255732  -0.526440   0.265839  10.0
third    0.877244  -3.066932  -1.739485  -0.708067  -0.295822  10.0
fourth   0.669795  -0.279458  -0.560824   1.053760   0.836211  10.0
fifth   10.000000  10.000000  10.000000  10.000000  10.000000  10.0

### more of series 

In [69]:
some_series = pd.Series(np.random.rand(5), index=['a','c','d','e','b'])
some_series

a    0.980342
c    0.650610
d    0.091008
e    0.636775
b    0.779902
dtype: float64

In [70]:
some_series[some_series>.5]

a    0.980342
c    0.650610
e    0.636775
b    0.779902
dtype: float64

In [71]:
print(note := " we can update a value in the series")
print()
some_series[some_series>.5] = 1
some_series

 we can update a value in the series



a    1.000000
c    1.000000
d    0.091008
e    1.000000
b    1.000000
dtype: float64

In [72]:
some_series[['a','d']]


a    1.000000
d    0.091008
dtype: float64

In [73]:
some_series[[0,3]]

a    1.0
e    1.0
dtype: float64

In [74]:
print(note := " we can sort the index of the series")
print()
some_series = some_series.sort_index()
some_series

 we can sort the index of the series



a    1.000000
b    1.000000
c    1.000000
d    0.091008
e    1.000000
dtype: float64

In [75]:
print(note := " we can also sort the series based on the values")
print()
some_series.sort_values()

 we can also sort the series based on the values



d    0.091008
a    1.000000
b    1.000000
c    1.000000
e    1.000000
dtype: float64

In [76]:
print(note := "we can use rank to get the ranking of values, showing the order of values ")
print()
print(note := " when we run sort etc, we shall have the values in order of rank")
print()
some_series.rank()

we can use rank to get the ranking of values, showing the order of values 

 when we run sort etc, we shall have the values in order of rank



a    3.5
b    3.5
c    3.5
d    1.0
e    3.5
dtype: float64

In [77]:
print(note := " we can also sort them in ascending order")
print()
some_series.sort_values(ascending=True)

 we can also sort them in ascending order



d    0.091008
a    1.000000
b    1.000000
c    1.000000
e    1.000000
dtype: float64

In [78]:
print(note := " we can use drop to remove a value from the series, remember that new series is created ")
print()
nss = some_series.drop('c')
print(nss)
print(some_series)

 we can use drop to remove a value from the series, remember that new series is created 

a    1.000000
b    1.000000
d    0.091008
e    1.000000
dtype: float64
a    1.000000
b    1.000000
c    1.000000
d    0.091008
e    1.000000
dtype: float64


In [79]:
some_series_1 = pd.Series(np.random.rand(6), index=['a','b','c','d','e','f'])
print()
some_series_1

a    0.055691
b    0.942937
c    0.059430
d    0.907734
e    0.721350
f    0.427127
dtype: float64

In [80]:
print(note := " we can do scalar operation on the series ")
print()
some_series_2 = some_series_1*2
some_series_2

 we can do scalar operation on the series 



a    0.111383
b    1.885874
c    0.118860
d    1.815468
e    1.442701
f    0.854253
dtype: float64

In [81]:
some_series_2 = some_series_2 - 1
some_series_2

a   -0.888617
b    0.885874
c   -0.881140
d    0.815468
e    0.442701
f   -0.145747
dtype: float64

In [82]:
print(note := " we can add two series ")
print()
print(some_series_2)
print(some_series_1)
some_series_2 + some_series_1

 we can add two series 

a   -0.888617
b    0.885874
c   -0.881140
d    0.815468
e    0.442701
f   -0.145747
dtype: float64
a    0.055691
b    0.942937
c    0.059430
d    0.907734
e    0.721350
f    0.427127
dtype: float64


a   -0.832926
b    1.828810
c   -0.821710
d    1.723201
e    1.164051
f    0.281380
dtype: float64

In [83]:
print(note := " but only when we have same index names can we see the result, else we shall see NaN")
print()
some_series + some_series_2

 but only when we have same index names can we see the result, else we shall see NaN



a    0.111383
b    1.885874
c    0.118860
d    0.906476
e    1.442701
f         NaN
dtype: float64

In [84]:
print(note := " we can use the pct_chnage to get the percentage change between series values")
print()
new_s = some_series.pct_change()
new_s

 we can use the pct_chnage to get the percentage change between series values



a         NaN
b    0.000000
c    0.000000
d   -0.908992
e    9.987992
dtype: float64

In [85]:
print(note := " we can use isnull to get the NaN values ")
print()
new_s.isnull()

 we can use isnull to get the NaN values 



a     True
b    False
c    False
d    False
e    False
dtype: bool

In [86]:
print(note := " we can directly drop the Nan values by dropna")
print()
new_s = new_s.dropna()
new_s

 we can directly drop the Nan values by dropna



b    0.000000
c    0.000000
d   -0.908992
e    9.987992
dtype: float64

In [87]:
new_s.min()

-0.9089915582127931

In [88]:
new_s.max()

9.987991667170489

In [89]:
new_s.std()

5.163305867747774

In [90]:
new_s.mean()

2.2697500272394238

In [91]:
print(note := " series supports describe that can be used to get some basic stats of data")
print()
new_s.describe()

 series supports describe that can be used to get some basic stats of data



count    4.000000
mean     2.269750
std      5.163306
min     -0.908992
25%     -0.227248
50%      0.000000
75%      2.496998
max      9.987992
dtype: float64

### more of dataframe 

In [92]:
some_df = pd.DataFrame(np.random.rand(20).reshape(4,5), index=['a','b','c','d'], columns=['c1','c2','c3','c4','c5'])
some_df

c1        c2        c3        c4        c5
a  0.203213  0.375913  0.145119  0.627456  0.343146
b  0.631627  0.836481  0.444227  0.646862  0.132346
c  0.055561  0.714243  0.900672  0.273218  0.711966
d  0.898253  0.518132  0.235600  0.195105  0.210697

In [93]:
print(note := " axis value is 0 for row, i.e. the default behaviour")
print()
some_df.drop('a', axis=0)

 axis value is 0 for row, i.e. the default behaviour



c1        c2        c3        c4        c5
b  0.631627  0.836481  0.444227  0.646862  0.132346
c  0.055561  0.714243  0.900672  0.273218  0.711966
d  0.898253  0.518132  0.235600  0.195105  0.210697

In [94]:
some_df.drop('c3', axis=1)

c1        c2        c4        c5
a  0.203213  0.375913  0.627456  0.343146
b  0.631627  0.836481  0.646862  0.132346
c  0.055561  0.714243  0.273218  0.711966
d  0.898253  0.518132  0.195105  0.210697

In [95]:
print(note := " we can select the data by col index")
print()
some_df['c1']

 we can select the data by col index



a    0.203213
b    0.631627
c    0.055561
d    0.898253
Name: c1, dtype: float64

In [96]:
print(note := " we can use the condition to select relevant data")
print()
some_df[(some_df['c3']>.5) & (some_df['c1']>.7)]

 we can use the condition to select relevant data



Empty DataFrame
Columns: [c1, c2, c3, c4, c5]
Index: []

In [97]:
print(note := " which is same as using loc")
print()
some_df.loc[(some_df['c3']>.5) & (some_df['c1']>.7)]

 which is same as using loc



Empty DataFrame
Columns: [c1, c2, c3, c4, c5]
Index: []

In [98]:
print(note := " we can also do conditional on the entire dataframe")
print()
print(some_df > .2)
print(some_df[some_df > .2])

 we can also do conditional on the entire dataframe

      c1    c2     c3     c4     c5
a   True  True  False   True   True
b   True  True   True   True  False
c  False  True   True   True   True
d   True  True   True  False   True
         c1        c2        c3        c4        c5
a  0.203213  0.375913       NaN  0.627456  0.343146
b  0.631627  0.836481  0.444227  0.646862       NaN
c       NaN  0.714243  0.900672  0.273218  0.711966
d  0.898253  0.518132  0.235600       NaN  0.210697


In [99]:
print(note := " we can do the scalar operation on the dataframe")
print()
print(some_df)
some_df_1 = some_df + 1
some_df_1

 we can do the scalar operation on the dataframe

         c1        c2        c3        c4        c5
a  0.203213  0.375913  0.145119  0.627456  0.343146
b  0.631627  0.836481  0.444227  0.646862  0.132346
c  0.055561  0.714243  0.900672  0.273218  0.711966
d  0.898253  0.518132  0.235600  0.195105  0.210697


c1        c2        c3        c4        c5
a  1.203213  1.375913  1.145119  1.627456  1.343146
b  1.631627  1.836481  1.444227  1.646862  1.132346
c  1.055561  1.714243  1.900672  1.273218  1.711966
d  1.898253  1.518132  1.235600  1.195105  1.210697

In [100]:
print(note := " we can add two dataframes")
print()
some_df_2 = some_df_1 + some_df
some_df_2

 we can add two dataframes



c1        c2        c3        c4        c5
a  1.406426  1.751826  1.290237  2.254911  1.686292
b  2.263254  2.672961  1.888454  2.293723  1.264693
c  1.111122  2.428487  2.801343  1.546436  2.423933
d  2.796506  2.036264  1.471199  1.390210  1.421393

In [101]:
print(note := " if the row/col numners doesnt match than we shall see the NaN")
print(note := " subset of row/col data shall be shown ") 
print()
some_df_2 + some_df[some_df['c3']>.5]

 if the row/col numners doesnt match than we shall see the NaN
 subset of row/col data shall be shown 



c1       c2        c3        c4        c5
a       NaN      NaN       NaN       NaN       NaN
b       NaN      NaN       NaN       NaN       NaN
c  1.166683  3.14273  3.702015  1.819654  3.135899
d       NaN      NaN       NaN       NaN       NaN

In [102]:
print(note := "we can use the add function to fill some value instread of NaN")
print()
print(some_df_2)
print(some_df)
some_df_2.add(some_df[some_df['c3']>.5], fill_value=0)

we can use the add function to fill some value instread of NaN

         c1        c2        c3        c4        c5
a  1.406426  1.751826  1.290237  2.254911  1.686292
b  2.263254  2.672961  1.888454  2.293723  1.264693
c  1.111122  2.428487  2.801343  1.546436  2.423933
d  2.796506  2.036264  1.471199  1.390210  1.421393
         c1        c2        c3        c4        c5
a  0.203213  0.375913  0.145119  0.627456  0.343146
b  0.631627  0.836481  0.444227  0.646862  0.132346
c  0.055561  0.714243  0.900672  0.273218  0.711966
d  0.898253  0.518132  0.235600  0.195105  0.210697


c1        c2        c3        c4        c5
a  1.406426  1.751826  1.290237  2.254911  1.686292
b  2.263254  2.672961  1.888454  2.293723  1.264693
c  1.166683  3.142730  3.702015  1.819654  3.135899
d  2.796506  2.036264  1.471199  1.390210  1.421393

In [103]:
print(note := "we can use the loc to get the particular row")
print()
x = some_df_2.loc['a']
x

we can use the loc to get the particular row



c1    1.406426
c2    1.751826
c3    1.290237
c4    2.254911
c5    1.686292
Name: a, dtype: float64

In [104]:
print(note := "we can do operation like addition, substraction etc between dataFrame and Series")
print()
print(x)
print(note := "the value of series shall be deducted from every row")
print()
some_df_2 - x

we can do operation like addition, substraction etc between dataFrame and Series

c1    1.406426
c2    1.751826
c3    1.290237
c4    2.254911
c5    1.686292
Name: a, dtype: float64
the value of series shall be deducted from every row



c1        c2        c3        c4        c5
a  0.000000  0.000000  0.000000  0.000000  0.000000
b  0.856828  0.921135  0.598216  0.038812 -0.421600
c -0.295304  0.676661  1.511106 -0.708475  0.737641
d  1.390080  0.284438  0.180962 -0.864701 -0.264899

In [105]:
new_df = pd.DataFrame(np.arange(30).reshape(6,5), index=['a','b','c','d','e','f'], columns=['c1','c2','c3','c4','c5'])
new_df

c1  c2  c3  c4  c5
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29

In [106]:
print(note := "pandas supports sum operation")
print(note := "default behaviour is to sum all the cols")
print()
new_df.sum()

pandas supports sum operation
default behaviour is to sum all the cols



c1    75
c2    81
c3    87
c4    93
c5    99
dtype: int64

In [107]:
print(note := "we can specify the axis as 1 to do sum based on rows")
print()
new_df.sum(axis=1)

we can specify the axis as 1 to do sum based on rows



a     10
b     35
c     60
d     85
e    110
f    135
dtype: int64

In [108]:
print(note := "we can pass the axis to get min of each row, here we using default")
print()
new_df.min()

we can pass the axis to get min of each row, here we using default



c1    0
c2    1
c3    2
c4    3
c5    4
dtype: int64

In [109]:
print(note := "we can also get the max values")
print()
new_df.max(axis=1)

we can also get the max values



a     4
b     9
c    14
d    19
e    24
f    29
dtype: int64

In [110]:
print(note := "we can get the index information for the minimum value")
print()
new_df.idxmin()

we can get the index information for the minimum value



c1    a
c2    a
c3    a
c4    a
c5    a
dtype: object

In [111]:
print(note := "we can get the index information for the max values")
print()
new_df.idxmax(axis=1)

we can get the index information for the max values



a    c5
b    c5
c    c5
d    c5
e    c5
f    c5
dtype: object

In [112]:
new_df.std()

c1    9.354143
c2    9.354143
c3    9.354143
c4    9.354143
c5    9.354143
dtype: float64

In [113]:
print(note := "pandas also has a describe function, which shows us some basic statistic information about the dataframe")
print()
new_df.describe()

pandas also has a describe function, which shows us some basic statistic information about the dataframe



c1         c2         c3         c4         c5
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   12.500000  13.500000  14.500000  15.500000  16.500000
std     9.354143   9.354143   9.354143   9.354143   9.354143
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     6.250000   7.250000   8.250000   9.250000  10.250000
50%    12.500000  13.500000  14.500000  15.500000  16.500000
75%    18.750000  19.750000  20.750000  21.750000  22.750000
max    25.000000  26.000000  27.000000  28.000000  29.000000

# That's all folks !!!

In [114]:
print(note := "we started with numpy basics")
print(note := "we learned about pandas dataframe and pandas series")
print(note := "in next session we will work on ukbb csv data and apply our learning from this session")

we started with numpy basics
we learned about pandas dataframe and pandas series
in next session we will work on ukbb csv data and apply our learning from this session
